from models.enums import ExtendedEnum


class LexingState(ExtendedEnum):
    START = 'START'

    LIT_STR = 'LIT_STR'
    LIT_STR_ESCAPE = 'LIT_STR_ESCAPE'

    LIT_CHAR = 'LIT_CHAR'
    LIT_CHAR_END = 'LIT_CHAR_END'

    LIT_INT = 'LIT_INT'
    LIT_INT_FIRST_ZERO = 'LIT_INT_FIRST_ZERO'

    LIT_FLOAT_START = 'LIT_FLOAT_START'
    LIT_FLOAT = 'LIT_FLOAT'
    LIT_FLOAT_EXP = 'LIT_FLOAT_EXP'
    LIT_FLOAT_PRE_END = 'LIT_FLOAT_PRE_END'
    LIT_FLOAT_END = 'LIT_FLOAT_END'

    OP_MINUS = 'OP_MINUS'
    OP_MINUS_2 = 'OP_MINUS_2'

    OP_DIV = 'OP_DIV'
    OP_NOT = 'OP_NOT'
    OP_ASSIGN = 'OP_ASSIGN'
    OP_AND = 'OP_AND'
    OP_OR = 'OP_OR'
    OP_LT = 'OP_LT'
    OP_ACCESS = 'OP_ACCESS'

    OP_GT = 'OP_GT'
    AFTER_GT = 'AFTER_GT'

    SL_COMMENT = 'SL_COMMENT'
    ML_COMMENT = 'ML_COMMENT'
    ML_COMMENT_END = 'ML_COMMENT_END'

    KW_FROM_STDIN = 'KW_FROM_STDIN'

    IDENTIFIER = 'IDENTIFIER'
